paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos de la base de datos
      tags:
        - Products
      responses:
        "200":
          description: "Cumples todo lo necesario para ver los productos"
        "400":
          description: "No estas registrado"
        "500":
          description: "Error interno de peticion a la base de datos"
  /api/products/pid:
      summary: Busca producto por id
      tags:
        - Products
      parameters:
      - name: pid
        in: query
        required: true
        description: Id del producto que quieres buscar
        schema:
          type: integer
      responses:
        "200":
          description: "Cumples todo lo necesario para ver el producto"
        "400":
          description: "No estas registrado"
        "500":
          description: "Error interno de peticion a la base de datos"       